# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_byte_group_io.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_if_post_fifo.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_of_pre_fifo.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_poc_cc.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_poc_tap_base.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_byte_lane.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_poc_edge_store.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_poc_meta.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_round_robin_arb.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_mux.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_lim.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_edge.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_cntlr.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_data.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_samp.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_4lanes.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ocd_po_cntlr.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_poc_top.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_arb_select.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_bank_compare.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_bank_queue.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_arb_row_col.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_bank_state.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_prbs_rdlvl.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_poc_pd.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_rdlvl.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_tempmon.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_wrcal.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_wrlvl_off_delay.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_prbs_gen.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_mc_phy.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_ck_addr_cmd_delay.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_wrlvl.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_oclkdelay_cal.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_dqs_found_cal.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_init.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_dqs_found_cal_hr.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_rank_common.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_bank_common.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_bank_cntrl.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_rank_cntrl.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_arb_mux.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_calib_top.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_mc_phy_wrapper.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_col_mach.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_bank_mach.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_rank_mach.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ecc/mig_7series_v2_3_ecc_merge_enc.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ecc/mig_7series_v2_3_ecc_gen.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ecc/mig_7series_v2_3_ecc_dec_fix.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ecc/mig_7series_v2_3_ecc_buf.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ecc/mig_7series_v2_3_fi_xor.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/phy/mig_7series_v2_3_ddr_phy_top.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/controller/mig_7series_v2_3_mc.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ui/mig_7series_v2_3_ui_rd_data.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ui/mig_7series_v2_3_ui_cmd.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ui/mig_7series_v2_3_ui_wr_data.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ui/mig_7series_v2_3_ui_top.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ip_top/mig_7series_v2_3_mem_intfc.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/clocking/mig_7series_v2_3_infrastructure.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/clocking/mig_7series_v2_3_tempmon.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/clocking/mig_7series_v2_3_iodelay_ctrl.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/clocking/mig_7series_v2_3_clk_ibuf.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/ip_top/mig_7series_v2_3_memc_ui_top_std.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/dram_mig.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/ip_dram/dram.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/define.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/lcdcon.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/dramcon.v
  /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/main.v
}
read_xdc /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/main.xdc
set_property used_in_implementation false [get_files /home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/main.xdc]

synth_design -top main -part xc7vx485tffg1761-2
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
