set_property SRC_FILE_INFO {cfile:/home/kobayashi/PCIe_test/branches/IEICE/bandwidth/DRAM/src/main.xdc rfile:../../../../src/main.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU36 [get_ports TXD]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM39 [get_ports {ULED[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN39 [get_ports {ULED[1]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR37 [get_ports {ULED[2]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT37 [get_ports {ULED[3]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR35 [get_ports {ULED[4]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP41 [get_ports {ULED[5]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP42 [get_ports {ULED[6]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU39 [get_ports {ULED[7]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {DDR3DQ[0]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13 [get_ports {DDR3DQ[1]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {DDR3DQ[2]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {DDR3DQ[3]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M12 [get_ports {DDR3DQ[4]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {DDR3DQ[5]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports {DDR3DQ[6]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {DDR3DQ[7]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports {DDR3DQ[8]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {DDR3DQ[9]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {DDR3DQ[10]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {DDR3DQ[11]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports {DDR3DQ[12]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {DDR3DQ[13]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {DDR3DQ[14]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {DDR3DQ[15]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {DDR3DQ[16]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {DDR3DQ[17]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {DDR3DQ[18]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14 [get_ports {DDR3DQ[19]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports {DDR3DQ[20]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {DDR3DQ[21]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {DDR3DQ[22]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {DDR3DQ[23]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {DDR3DQ[24]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13 [get_ports {DDR3DQ[25]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {DDR3DQ[26]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {DDR3DQ[27]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {DDR3DQ[28]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {DDR3DQ[29]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {DDR3DQ[30]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {DDR3DQ[31]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24 [get_ports {DDR3DQ[32]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B23 [get_ports {DDR3DQ[33]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B27 [get_ports {DDR3DQ[34]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports {DDR3DQ[35]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports {DDR3DQ[36]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {DDR3DQ[37]}]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25 [get_ports {DDR3DQ[38]}]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24 [get_ports {DDR3DQ[39]}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E24 [get_ports {DDR3DQ[40]}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports {DDR3DQ[41]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {DDR3DQ[42]}]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C25 [get_ports {DDR3DQ[43]}]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {DDR3DQ[44]}]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D22 [get_ports {DDR3DQ[45]}]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {DDR3DQ[46]}]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22 [get_ports {DDR3DQ[47]}]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A30 [get_ports {DDR3DQ[48]}]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D27 [get_ports {DDR3DQ[49]}]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A29 [get_ports {DDR3DQ[50]}]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C28 [get_ports {DDR3DQ[51]}]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D28 [get_ports {DDR3DQ[52]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B31 [get_ports {DDR3DQ[53]}]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A31 [get_ports {DDR3DQ[54]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A32 [get_ports {DDR3DQ[55]}]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E30 [get_ports {DDR3DQ[56]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F29 [get_ports {DDR3DQ[57]}]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F30 [get_ports {DDR3DQ[58]}]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F27 [get_ports {DDR3DQ[59]}]
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C30 [get_ports {DDR3DQ[60]}]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E29 [get_ports {DDR3DQ[61]}]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F26 [get_ports {DDR3DQ[62]}]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D30 [get_ports {DDR3DQ[63]}]
set_property src_info {type:XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {DDR3ADDR[15]}]
set_property src_info {type:XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {DDR3ADDR[14]}]
set_property src_info {type:XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports {DDR3ADDR[13]}]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {DDR3ADDR[12]}]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {DDR3ADDR[11]}]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports {DDR3ADDR[10]}]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {DDR3ADDR[9]}]
set_property src_info {type:XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {DDR3ADDR[8]}]
set_property src_info {type:XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {DDR3ADDR[7]}]
set_property src_info {type:XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {DDR3ADDR[6]}]
set_property src_info {type:XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {DDR3ADDR[5]}]
set_property src_info {type:XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {DDR3ADDR[4]}]
set_property src_info {type:XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {DDR3ADDR[3]}]
set_property src_info {type:XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {DDR3ADDR[2]}]
set_property src_info {type:XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {DDR3ADDR[1]}]
set_property src_info {type:XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {DDR3ADDR[0]}]
set_property src_info {type:XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {DDR3BA[2]}]
set_property src_info {type:XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {DDR3BA[1]}]
set_property src_info {type:XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {DDR3BA[0]}]
set_property src_info {type:XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {DDR3RAS_N}]
set_property src_info {type:XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {DDR3CAS_N}]
set_property src_info {type:XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {DDR3WE_N}]
set_property src_info {type:XDC file:1 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C29 [get_ports {DDR3RESET_N}]
set_property src_info {type:XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {DDR3CKE[0]}]
set_property src_info {type:XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {DDR3ODT[0]}]
set_property src_info {type:XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports {DDR3CS_N[0]}]
set_property src_info {type:XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {DDR3DM[0]}]
set_property src_info {type:XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {DDR3DM[1]}]
set_property src_info {type:XDC file:1 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {DDR3DM[2]}]
set_property src_info {type:XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {DDR3DM[3]}]
set_property src_info {type:XDC file:1 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C23 [get_ports {DDR3DM[4]}]
set_property src_info {type:XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {DDR3DM[5]}]
set_property src_info {type:XDC file:1 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C31 [get_ports {DDR3DM[6]}]
set_property src_info {type:XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F31 [get_ports {DDR3DM[7]}]
set_property src_info {type:XDC file:1 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {CLK_P}]
set_property src_info {type:XDC file:1 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {CLK_N}]
set_property src_info {type:XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW40 [get_ports {RST_X_IN}]
set_property src_info {type:XDC file:1 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {DDR3DQS_P[0]}]
set_property src_info {type:XDC file:1 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {DDR3DQS_N[0]}]
set_property src_info {type:XDC file:1 line:728 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {DDR3DQS_P[1]}]
set_property src_info {type:XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J12 [get_ports {DDR3DQS_N[1]}]
set_property src_info {type:XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {DDR3DQS_P[2]}]
set_property src_info {type:XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {DDR3DQS_N[2]}]
set_property src_info {type:XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {DDR3DQS_P[3]}]
set_property src_info {type:XDC file:1 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {DDR3DQS_N[3]}]
set_property src_info {type:XDC file:1 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A26 [get_ports {DDR3DQS_P[4]}]
set_property src_info {type:XDC file:1 line:770 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A27 [get_ports {DDR3DQS_N[4]}]
set_property src_info {type:XDC file:1 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports {DDR3DQS_P[5]}]
set_property src_info {type:XDC file:1 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {DDR3DQS_N[5]}]
set_property src_info {type:XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B28 [get_ports {DDR3DQS_P[6]}]
set_property src_info {type:XDC file:1 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B29 [get_ports {DDR3DQS_N[6]}]
set_property src_info {type:XDC file:1 line:800 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E27 [get_ports {DDR3DQS_P[7]}]
set_property src_info {type:XDC file:1 line:806 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E28 [get_ports {DDR3DQS_N[7]}]
set_property src_info {type:XDC file:1 line:812 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {DDR3CK_P[0]}]
set_property src_info {type:XDC file:1 line:818 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports {DDR3CK_N[0]}]
set_property src_info {type:XDC file:1 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:823 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:824 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:825 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:826 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y23 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:827 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y22 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:828 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y21 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:829 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:830 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:831 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:832 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:834 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:835 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:836 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:837 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:841 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:842 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:843 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:844 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:848 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:849 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:850 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:851 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:852 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y23 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:853 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y22 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:854 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y21 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:855 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:856 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:857 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:858 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:860 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:861 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:862 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:863 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:864 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:865 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:866 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:867 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:869 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:870 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:871 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:873 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:874 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:875 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:877 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y243 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:878 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y231 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:879 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y219 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:880 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y207 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:881 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y343 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:882 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y331 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:883 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y319 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:884 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y307 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:886 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y5 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:XDC file:1 line:887 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y5 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:XDC file:1 line:914 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:XDC file:1 line:915 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:XDC file:1 line:919 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
