webtalk_init -webtalk_dir C:/Users/kobayashi/Desktop/FPGASort/trunk/vivado/vivado.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 11 02:55:48 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2014.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1071353" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174123318_174133242_210592318_242" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8c439290-c6fb-4b4c-ba66-dce3ff7f76ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "176a6212-07d4-4df7-8527-d69fbd15be57" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-SMT1/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "33687093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1863655904 -regid "174123318_174133242_210592318_242" -xml C:/Users/kobayashi/Desktop/FPGASort/trunk/vivado/vivado.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/kobayashi/Desktop/FPGASort/trunk/vivado/vivado.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/kobayashi/Desktop/FPGASort/trunk/vivado/vivado.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
