# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kobayashi/PCIe_test/branches/IEICE/data_compression/4-way_2-tree/src/ip_pcie/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kobayashi/PCIe_test/branches/IEICE/data_compression/4-way_2-tree/src/ip_pcie/source/PCIeGen2x8If128-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/kobayashi/PCIe_test/branches/IEICE/data_compression/4-way_2-tree/src/ip_pcie/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/kobayashi/PCIe_test/branches/IEICE/data_compression/4-way_2-tree/src/ip_pcie/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kobayashi/PCIe_test/branches/IEICE/data_compression/4-way_2-tree/src/ip_pcie/source/PCIeGen2x8If128-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/kobayashi/PCIe_test/branches/IEICE/data_compression/4-way_2-tree/src/ip_pcie/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
