# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128.xci
set_property is_locked true [get_files /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top PCIeGen2x8If128 -part xc7vx485tffg1761-2 -mode out_of_context
rename_ref -prefix_all PCIeGen2x8If128_
write_checkpoint -noxdef PCIeGen2x8If128.dcp
catch { report_utilization -file PCIeGen2x8If128_utilization_synth.rpt -pb PCIeGen2x8If128_utilization_synth.pb }
if { [catch {
  file copy -force /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.runs/PCIeGen2x8If128_synth_1/PCIeGen2x8If128.dcp /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.ip_user_files/ip/PCIeGen2x8If128]} {
  catch { 
    file copy -force /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128_stub.v /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.ip_user_files/ip/PCIeGen2x8If128
  }
}

if {[file isdir /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.ip_user_files/ip/PCIeGen2x8If128]} {
  catch { 
    file copy -force /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/src/ip_pcie/PCIeGen2x8If128_stub.vhdl /home/kobayashi/PCIe_test/branches/IEICE/8-way_2-tree/vivado/vivado.ip_user_files/ip/PCIeGen2x8If128
  }
}
